#!/bin/bash
# iMessage Exporter - Quick Start Guide

echo "════════════════════════════════════════════════════════════"
echo "            iMessage Exporter v1.0 - Setup"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "This will help you set up the iMessage Exporter."
echo ""
echo "📋 REQUIRED PERMISSIONS:"
echo ""
echo "You need to grant Terminal these permissions:"
echo "  1. Full Disk Access (to read Messages database)"
echo "  2. Contacts Access (to match phone numbers to names)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Press ENTER to open System Settings..." 

# Open System Settings to the right page
open "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles"

echo ""
echo "✓ System Settings opened"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. In Full Disk Access:"
echo "   • Click the 🔒 lock and enter your password"
echo "   • Click the + button"
echo "   • Go to Applications → Utilities → Terminal"
echo "   • Enable the checkbox"
echo ""
echo "2. Then go to Contacts (in the left sidebar):"
echo "   • Click the + button"  
echo "   • Add Terminal again"
echo "   • Enable the checkbox"
echo ""
echo "3. Close System Settings"
echo "   • QUIT and REOPEN Terminal"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Press ENTER when you've completed these steps..." 

echo ""
echo "Great! Now you can run the exporter:"
echo ""
echo "  python3 imessage_archive.py"
echo ""
echo "════════════════════════════════════════════════════════════"
